baseURL = "https://blog.drmatthew.org"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Daniel's Maker Blog"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
pagination.pagerSize = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["collections","collection"]
dateFormat = "January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = false
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = true
authorInfo = "She was born to be free, let her run wild in her own way and you will never lose her."
description="Your can add your website description here."
previewCardImagePlacement = "middle"
unsafe = true

[markup.goldmark.renderer]
    unsafe = true

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params.Author]
  name = "Daniel R Matthew"
  website = "https://blog.drmatthew.org/"
  email = "daniel@compunique.com"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #threads = "username"
  #linkedin = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"


[[menu.main]]
    name = "Recent Projects"
    url = "/collections/"
    weight = 1


[[menu.main]]
    name = "Project Categories"
    url = "/tags"
    weight = 2



[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3



